# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RWReactivePlayground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'ReactiveObjC', '~> 3.1.0'

  target 'RWReactivePlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
